### ISSUE TITLE
Add draft PR for CONTRIBUTING.md

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developerdao.com#112]
Currently we have a working google document around "Development Guidelines" to act as a base for people looking to contribute to the project.  As a takeaway item from the last community meeting we want to draft a PR to update the CONTRIBUTING.md file so that developers have a better understanding of how best contribute.

**Comment by codingwithmanny** [comment]
Yes to this! I think we might need a TL;DR version of it as well or maybe create a version like that.

**Comment by dheavy** [comment]
Maybe as a rule of thumb we should assign reviewers to PRs as well? 
Who should review (and who should merge) PR #88 that closes this issue?

**Comment by with-heart** [comment]
> Maybe as a rule of thumb we should assign reviewers to PRs as well?

I think for the most part we've been pretty good about reviewing! Most PRs so far have had reviews from maintainers and non-maintainers alike. This PR is just a weird case because it's being worked on outside of GitHub. I had asked @narbs91 to open it as a draft PR on GitHub just so people without access to it (which includes myself) could read it. 

> Who should review (and who should merge) PR #115 that closes this issue?

I'm planning to review it soon just to get my thoughts out there, but it's a draft for a reason! We're just collecting feedback on it so we can just adjust it, but I don't think there's any real sense of urgency to get it merged. And I think that's probably fine. We'll get it figured out when we're ready ya know?

**Comment by dheavy** [comment]
Sure @with-heart! I’m sorry, maybe these questions sounded a little inquisitive in hindsight :) 
I was just afraid of stepping into someone’s way if I jumped on some unassigned PRs. Having just arrived here, I’m slowly getting acquainted. Thanks for taking the time for proving directions to newcomers like me 👍🏽 Super appreciated 🙂

**Comment by with-heart** [comment]
> I’m sorry, maybe these questions sounded a little inquisitive in hindsight :)

NO not at all! You should be inquisitive! That was a good question that deserved a good explanation of what I'm thinking with this at least. 

I kinda look at it like some initiatives and priorities matter more to us than others, we can tell when they matter because if it matters someone will take the time to carry it over the finish line, and it's okay if some things take longer to become a priority than others. If it's not okay, then it leads to people getting burnt out, which I've experienced too many times myself (through both job and open source), so I try to encourage attitudes that avoid that :)

**Comment by dheavy** [comment]
I like your philosophy _a lot_ 🙂
