### ISSUE TITLE
[Feature]: Caching proxy for Resources Airtable

### ISSUE THREAD

**Issue by gjsyme** [Developer-DAO/developerdao.com#166]
### Context / Background / How This Idea Came To Fruition

The Airtable API has a static (can't be purchased out of, not that we would be likely to do that anyway) rate limit of 5 requests per second. There is, fortunately, a backoff built into the JS SDK but it's not a good user experience.
They recommend a caching proxy in order to avoid getting rate limited.
Relates to PR #161 

### Problem / Opportunity

Avoid getting rate limited by going over 5 requests per second on the Airtable API for Resources

### Proposed Solution / How It Can Be Improved

Caching Proxy solution. Is there a cost-effective hosted or self-hosted solution available?

### Testing the changes

- Airtable values able to be queried over 5 times per seconds (2+ page loads at the same time)
- Tracking updates of underlying data (in airtable)
- Unforeseen cases

**Comment by Neumand** [comment]
I could take a stab at this. I know that **brandonl.eth** mentioned this yesterday so if he wants to take care of it that's cool with me!

My understanding is that instead of fetching the resources client-side with our custom hook, we'll move the logic to the `getStaticProps` call and add the `revalidate` field to rebuild the page whenever we add new resources. I don't have any experience with Airtable but on my personal site I fetch data in Notion similarly :)

**Comment by gjsyme** [comment]
@Neumand I've added you to my fork so that you should be able to commit there; this way you can push to the branch that the PR is based upon and get it in. Please go ahead and knock that out as you're able; I'll take a look to clean it up and get the PR submitted by the end of the weekend if you don't get a chance.

**Comment by Neumand** [comment]
@gjsyme I made a change so that we no longer need the `useAirtableresources`. Instead, I create a `getAirtableResources` function in the new `/lib/airtable.ts` that will be called in the `getStaticProps`.

I kept the majority of your logic, basically just removing anything that was UI-focused. I'm out of time for today unfortunately but this should get you going for the rest.

I'll have some more time this weekend if you want to ping me.

**Comment by gjsyme** [comment]
that was all i needed - i can see it working on localhost and with this structure we don't even have to put the keys in a NEXT_PUBLIC. i tweaked it (slow down the requests even more and use the server side constants) and will get the PR up pending the vercel updates. thank you!

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues.  As such i'll be closing this issue.  Thanks for the interest in the website but tune back a little later when the new direction has been established
