### ISSUE TITLE
[Feature]: IPFS-based front-end

### ISSUE THREAD

**Issue by invinciblemax** [Developer-DAO/developerdao.com#175]
### Context / Background / How This Idea Came To Fruition

I come from 4EVERLAND,I am also a member of DeveloperDao #4070 , I have been advocating and trying to advance web3 through my own efforts. 
When I go through the official website and mint my token, I noticed that Vercel provides hosting services for our current website. 
I wonder why we can't have an IPFS-based front-end that better illustrates the concept of web3？As a case in point, better influence other developers in the community.
In communicating with the community, it made me feel like it was a meaningful thing to do that. So I am writing my proposal here.
Lots of projects in the market is now deploying and hosting their own front-end via IPFS + Cloudflare. 
4EVERLAND offers a simpler solution. Provide one-stop service for projects.
Helps developers achieve IPFS-based front-end deployment and hosting in 3 minutes, and is compatible with web2 access and global acceleration.

### Problem / Opportunity

Why we need an IPFS-based front-end?
1. The IPFS-based front-end is not subject to any centralized servers that could cause downtime or data security problems.
2. Helping developers achieve a return to data sovereignty.
3. Providing more possibilities for decentralized or unlimited front ends.
4. Advancing web3.

### Proposed Solution / How It Can Be Improved

If the community recognizes 4EVERLAND, I think we will advance the cooperation from two teams.
4EVERLAND：
1. Will provide free and stable hosting service for Developer Dao.（Although we are now free, Developer Dao will still enjoy the free service when our paid version goes live）
2. Will be a close partner of Developer Dao to promote web3 (either sponsorship or technical services).
3. Every certified developer of the website team can join our whitelist and enjoy the long-term support and sponsorship of 4EVERLAND.
4. Providing deployment support for all devs in the Developer Dao community. (I'm still working on the application with the team, but it won't be too much of a problem because we always encourage any developer to be able to use a decentralized service to help build their own applications）
Website team:
1. Deploy IPFS-based front-end and keep it updated for operations and maintenance.
2. Advancing web3 with 4EVERLAND.

### Testing the changes

We are willing to provide full technical support, if the deployment is started.
Besides, If the team finds a bug in the platform, you can get a reward through our 'bug bounty'.

### Additional Information

You can get more imformation vis these link.
● Website: https://www.4everland.org/
● Twitter: https://twitter.com/4everland_org
● Telegram: https://t.me/org_4everland
● Medium: https://4everland.medium.com/
● Discord: https://discord.gg/sxtHDvvpuT
● Reddit: https://www.reddit.com/user/4everland_org/
● Email: contact@4everland.org

**Comment by codingwithmanny** [comment]
Hi @invinciblemax took a look at the feature set. It looks great but could you elaborate on how 4everland might handle the following:

**1 - Non-persisted individually deployed PRs:**

Often we need to test a deployed pull request for others to take a look at a proposed deployment.
It would be easy just to run the repository locally but some members are not 100% familiar with the code or we want to be able to easily perform smoke tests to verify that functionality is working correctly. It would also be a concern in the case that code reviews don't catch a bad actor that replaces the wallet address for minting, which potentially could be shared and convince others that this is coming from a legitimate domain, even from a PR link.

**2 - Next.js SSR for multiple languages:**

I can't say I'm too familiar with the SSG side of Next.js, but if I remember correctly, we tried to run a deployment which generated all the SSG pages prior, but found that the deployment took too long. Correct me if I'm wrong, but I'm assuming because it's static with IPFS, that the files wouldn't be SSR.

Additionally, if SSR is not a possibility, how would the service handle secret keys server side (not exposed on the FE)? This is something we could be considering later for some other services we intend to use.

**3 - IPFS Storage:**

Forgive me if I'm not too familiar with Swarm, but how does it compare to Arweave.org or Filecoin? Are the mechanism for deletion (removing pointing to a file)?

**4 - Collaboration and automatic deployments with forks:**

Building on point 1, does the service offer automatic deployments that wouldn't require one user to deploy the site, and if it's solely a branch or a fork, is there a way to not store that data on IPFS, as it would not be used and ideally not indexed for search engines. I realize you could just do a `robot.txt` but ideally we don't store anything permanently.

Additionally, is there a way that more than one use might have access to the deployment configuration?

**Further Context:**
I cannot speak for others, as it's also a community decision, and while I do like new technology, I have a feeling that this will be hard to adopt as it is not something that most developers are use to. I realize that IPFS is not new, but it's documentation and that of 4everland doesn't seem as robust as Vercel (which helps tremendously with those who are both new to development and new to web3). We did also go through a few iterations for the technology before deciding on Next.js with Vercel, and the main reason was more ease of use, docs, and adoption (the free hosting also did help).

I hope that 4everland does pickup and the docs definitely grow (both in code implementations and also blog posts for different deployment scenarios).

My current personal opinion (which may change) is that I'm leaning towards continuing with Vercel, but I would welcome the conversation and what others think.

**Comment by narbs91** [comment]
Hi @invinciblemax thank you for putting this proposal together!  I took a look around the site as well and do think 4EVERLAND seems like a promising product with a bright future; however, it looks too bleeding edge for me to be comfortable to port the site over.  My questions around the product are more or less in line with what Manny has written above. 

I'm all for innovation and decentralization but i don't know if now is the right time to make that switch over.  Maybe this is something we can look to do a small POC around to see how something like this will work as I've never had any experience with a truly decentralized app.  Forward looking, we certainly could revisit a partnership/sponsorship but my feeling at the moment is maybe it's too early.  I'd love to hear what the rest of the gang thinks too

**Comment by embiem** [comment]
I know that most dApps still host on Web2 providers (mainly because of the problems already described above), but have essentially the same site deployed on IPFS as well. 

IMO this might be an option for D_D's site as well: to essentially have a CD stream that builds the static site and pushes it to IPFS as well as deploys to vercel.

**Comment by codingwithmanny** [comment]
@embiem I think what you're suggesting is SSG if I'm not mistaken, but correct me if I'm wrong.

If so, then an issue is the build time (we saw previously), to generate all the pages for all languages.

**Comment by embiem** [comment]
@codingwithmanny true, Next.js dynamic routing for i18n [won't work with SSG](https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation).

As this would be a limitation preventing us to serve via IPFS, we could decide to only support English on the IPFS deployment.

This definitely has no priority, but in general I do believe that we should try to be as decentralized as possible. Working on this could also lead to a guide in our knowledge base on how to deploy a dApp in the Web3 way.

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues.  As such i'll be closing this issue.  Thanks for the interest in the website but tune back a little later when the new direction has been established
