### ISSUE TITLE
[Feature]: Add LinkedIn link to website footer

### ISSUE THREAD

**Issue by jcstein** [Developer-DAO/developerdao.com#231]
### Context / Background / How This Idea Came To Fruition

https://www.linkedin.com/company/developer-dao/ - 13 May 2022 Town Hall

### Problem / Opportunity

Growing our network

### Proposed Solution / How It Can Be Improved

https://www.linkedin.com/company/developer-dao/

### Testing the changes

https://www.linkedin.com/company/developer-dao/

**Comment by rai-rakesh** [comment]
Anyone working on this? I can pick this up.

**Comment by AurelienConte** [comment]
Hi, since the PR has no response i have taken the job by myself (sorry @rai-rakesh if i disturb you). 
This is my first contribution to the project so any review are welcome.

I haven't see any tests about the frontend so i didn't add test about the linkedin icon, maybe it can be a new issue if it's not created already ...
