### ISSUE TITLE
Validate token number from url parameter

### ISSUE THREAD

**Issue by fmoliveira** [Developer-DAO/developerdao.com#98]
The search input already has a validation that disallows typing token numbers greater than 8000, our maximum token number.

However, we can still type an arbitrary number in the URL and the page shows as if the token existed and is available to be claimed. This may look like trolling for people familiar with the token limit, but otherwise, having an error message saying something like "Invalid token number" would be helpful.

Steps to reproduce:
- Access https://www.developerdao.com/?id=150258
- The NFT image is rendered, but it should error instead

![Screen Shot 2021-09-20 at 11 21 44 PM](https://user-images.githubusercontent.com/3985462/134102111-7a9fa47b-56f2-4bdb-8a87-a9a922229717.png)

**Comment by fmoliveira** [comment]
Sounds liike a good first issue?

**Comment by fmoliveira** [comment]
Sounds like a good first issue?

**Comment by moiz-lakkadkutta** [comment]
@fmoliveira hey i would like work on this

**Comment by narbs91** [comment]
This is still pending feedback from Vercel support.  I have sent a chaser email this morning and am awaiting a response

**Comment by narbs91** [comment]
As we are shifting the purpose of the website pending a decision from the design guild we are putting a pause on all non maintenance/house keeping issues.  As such i'll be closing this issue.  Thanks for the interest in the website but tune back a little later when the new direction has been established.

I will however add the localization fix in a follow up PR since that is re-usable in any future direction we take with the site
